NUMPY 

We use numpy to perform numerical operation .then u may think we already have a list and 
what is the need for a library,why coz normal list is slower in excution and it took so 
much space also.here its need for numpy it is backuped by c programming,so it is very 
fast compared to normal python list,and it only takes less space also
numpy can be used to perform direct operation(vectorising)



In [ ]:
!pip install numpy

^C


   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---- ----------------------------------- 1.3/12.3 MB 11.4 MB/s eta 0:00:01
   ---------- ----------------------------- 3.1/12.3 MB 12.4 MB/s eta 0:00:01
   ----------------- ---------------------- 5.5/12.3 MB 10.2 MB/s eta 0:00:01
   -------------------- ------------------- 6.3/12.3 MB 8.6 MB/s eta 0:00:01
   ----------------------- ---------------- 7.3/12.3 MB 8.1 MB/s eta 0:00:01
   --------------------------- ------------ 8.4/12.3 MB 7.5 MB/s eta 0:00:01
   ---------------------------- ----------- 8.9/12.3 MB 7.1 MB/s eta 0:00:01
   ------------------------------ --------- 9.4/12.3 MB 6.3 MB/s eta 0:00:01
   -------------------------------- ------- 10.0/12.3 MB 5.7 MB/s eta 0:00:01
   --------------------------------- ------ 10.2/12.3 MB 5.4 MB/s eta 0:00:01
   ---------------------------------- ----- 10.7/12.3 MB 5.0 MB/s eta 0:00:01
   ------------------------------------ --- 11.3/12.3 MB 4.8 MB/s eta 0:00:01


[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
import numpy as np
import sys
arr=[1,2,3,4]
a=np.array(arr)
print(arr)
print(a)
print(sys.getsizeof(arr))
print(a.nbytes)
 #here look at the space things numpy array only takes lesser than half of the space obtained by list

[1, 2, 3, 4]
[1 2 3 4]
88
32


In [ ]:
#but the import thing is np array only take single datatypes but the list have multidata types
lst=[1,'hi']
arr=np.array(lst)
print(lst)
print(arr) #here the np automatically convert every element into string 

[1, 'hi']
['1' 'hi']


In [13]:
#dimension and shape 

#dimension means like if the number 32 iteself is a 0 dimension but considering the array[1,2,3,4] its actually
# 1 dimensional ,we have 2 dimensional also [[1,2,3,4][2,3,4,5]]
arr=np.array(32)
print(arr.ndim) #0 coz its only a number

arr=np.array([1,2,3,4])
print(arr.ndim) #1 coz its 1 dimensional array

arr=np.array([[]])
print(arr.ndim) #2 its 2 dimensional array 

# here the most import thing is that the dimension mainly depends on the number of brackets

arr=np.array([[[]]])
print(arr.ndim) # 3 its 3 dimensional array

#shape show the number of rows and colums 

print(arr.shape)

0
1
2
3
(1, 1, 0)


In [ ]:
a = np.array([[1,2,3],[1,2,3]])
#properties of np array
a.ndim     # number of dimensions
a.shape    # size in each dimension
a.size     # total elements
a.dtype    # data type
a.itemsize # memory per element

print(a.ndim) #no of dimension
print(a.shape) #no of rows and columns
print(a)
print(a.size) #rows*colums
print(a.dtype)
print(a.itemsize) #memory per element
print(a.nbytes) # total memory






2
(2, 3)
[[1 2 3]
 [1 2 3]]
6
int64
8
48


🔹 4️⃣ Array Creation Methods

Creating arrays is extremely important because everything in NumPy starts from this.

There are 5 main ways to create arrays:

From Python objects

Using predefined shape functions

Using range-based functions

Using random functions

From existing data (copying / reshaping / reading buffers)

Let’s go one by one.

In [ ]:
#4.1 Creating Arrays from Python Objects

#we can convert our python list into numpy array

arr=np.array([[1,2,3],[1,2,0]])
print(arr.ndim,arr.size,arr.shape)
# What happens internally?

# Python list → converted to contiguous C array

# All elements converted to same dtype

# Stored in contiguous memory block 
arr=np.array([1,2.5,3,5])
print(arr) #every thing converted into float

2 6 (2, 3)
[1.  2.5 3.  5. ]


dtype('float64')

In [ ]:
# #4.2 Predefined Shape Functions

# These functions create arrays without manually writing values.
np.zeros((2,3))
np.ones((2,2))
np.full((2,2), 7)
np.eye(3)
np.identity(3)

arr=np.zeros((3,3))
print(arr)

arr=np.ones((2,2))
print(arr) 

arr=np.full((3,4),7)
print(arr)

arr=np.eye(3,k=-2)
print(arr)

arr=np.identity(3)
print(arr)

arr=np.empty((2,6))
print(arr)
#np.empty gives unpredictable values, while np.zeros gives a clean slate of zeros.



[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
[[0. 0. 0.]
 [0. 0. 0.]
 [1. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[3.5e-323 3.5e-323 3.5e-323 3.5e-323 3.5e-323 3.5e-323]
 [3.5e-323 3.5e-323 3.5e-323 3.5e-323 3.5e-323 3.5e-323]]


In [76]:
# 4.3 Range-Based Creation
# 🔹 np.arange()

# Like Python range but returns array.

arr=np.arange(1,10,2)#start,end,step 
print(arr)

arr=np.linspace(0,1,5)  #np.linspace is a NumPy function used to generate evenly spaced numbers over a         specified interval. It’s especially handy when you want a sequence of values between two endpoints.
print(arr)
# In short: use np.logspace when you want values that grow exponentially (common in scientific computations, plotting frequency scales, etc.), while np.linspace is for straight linear spacing.

arr=np.logspace(0,2,5,dtype=int) 
# Generate 5 numbers between 10^0 and 10^2
print(arr)


[1 3 5 7 9]
[0.   0.25 0.5  0.75 1.  ]
[  1   3  10  31 100]


In [111]:
# 4.4 Random Array Creation

import numpy as np
  # reproducible results
np.random.seed(5)
print(np.random.rand(3,2))       # 3 random floats [0,1)
#print(np.random.randint(1, 10, 5))  # 5 random integers
#print(np.random.choice(['A','B','C'], 3))  # random choice
# What is use of random.seed ?
# Computers cannot generate true randomness. Instead they generate: Deterministic numbers that look random
# These numbers are generated using: # A mathematical formula
# Starting from an initial number called the seed
# 🔹 What is a Seed?
# A seed is just a starting number for the random generator.
# Think like this:
# If the seed is 10,
# the generator will always produce the same sequence.
# If the seed is 42,
# it will produce another fixed sequence.

#print(np.random.randn(5,5))
#np.random.randint(1,10,(2,3))



[[0.22199317 0.87073231]
 [0.20671916 0.91861091]
 [0.48841119 0.61174386]]


In [ ]:
# 🔹 5. Data Types in NumPy

# NumPy supports:

# int8, int16, int32, int64

# float16, float32, float64

# bool

# complex 

In [126]:
# # Indexing and Slicing in NumPy (Very Important)

# 1D Array Indexing
import numpy as np

a = np.array([10, 20, 30, 40, 50])

print(a[1:4:2]) 
b=a[1:4] 

#here it share the view that means if i change b later it will also change in a
print(id(a))
print(id(b))
a=[1,2,3,4,5]
l=a
print(id(a))
print(id(l))



[20 40]
1742437650512
1742471826960
1742474226944
1742474226944


In [142]:
# 2D Array Indexing

arr=np.array([[1,2,3],[1,2,3],[1,2,3]])
for i in range(2):
    for j in range(3):
        print(arr[i,j])
print(arr[:,:]) #row,column

print(arr[:,:2]) #limit row to 2 rows limit column to 2


1
2
3
1
2
3
[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 2]
 [1 2]
 [1 2]]


In [ ]:
#  — Boolean Indexing
arr=np.array([1,2,3,4,5])
print(arr[arr>2])

[3 4 5]


In [ ]:
# -Fancy Indexing
print(arr[[0,3]]) #print the elements at the 0 and 3 index

[1 4]


In [146]:
# - Reshaping
arr=np.arange(6)
print(arr)
print(arr.shape)
print(arr.reshape(2,3))


[0 1 2 3 4 5]
(6,)
[[0 1 2]
 [3 4 5]]


In [153]:
# Row 1 → 0 1 2
# Row 2 → 3 4 5

# NumPy fills row by row (C-order).
# NumPy can calculate one dimension automatically.

print(arr.reshape(-1, 2))

[[0 1]
 [2 3]
 [4 5]]


In [ ]:
b = np.array([[1,2,3],
              [4,5,6]])
print(b.flatten()) #not a view
print(b.ravel()) #its a view


[1 2 3 4 5 6]
[1 2 3 4 5 6]
